# -*- coding: utf-8 -*-
"""example_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7zAFlbCcH4WOn5mDYxQtxVtqTSYzeze

# Set up
"""

!git clone https://github.com/ShiqiZ1208/Emotion_diffusion_project.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Emotion_diffusion_project

!pip install -r requirement.txt

"""# dialouge form input reuslt"""

!ls

from Emotiondiffusionpipline import sdpipline
from Emotion_detection import diasum
dialogue = """Man: [Looking out at the sunset] "Isn't it beautiful? The way the sky is painted with all those colors... It feels like the whole world is holding its breath."

Woman: [Smiling, watching the sunset] "It does. It's like a reminder that even the most fleeting moments can be beautiful, if you really take the time to appreciate them."

Man: [Turns to her, his voice soft] "Do you ever think about how love is kind of like a sunset?"

Woman: [Raises an eyebrow, intrigued] "A sunset? How so?"

Man: "Well, it's something that you can't hold onto forever. It’s always passing, slipping through your fingers. But if you’re lucky, you get to witness it. And even when it's gone, it leaves something behind—this warmth, this memory."

Woman: [Thoughtfully] "That’s a beautiful way of looking at it. But I also think that love is more like the sea. It’s constant, always there, even if we don’t see it in every moment. It has its calm and its storms, but it’s never really gone."

Man: [Chuckles softly] "I like that. The sea… It always comes back. Kind of like how I feel about you."

Woman: [Blushing slightly, looking at him] "I guess we both need the waves to remind us sometimes. And the sunsets, too."

Man: [Leans closer, gazing at the horizon] "Yeah, the sunsets... they remind us that every day is a chance to start fresh. Even when things seem to be fading, something new is always on the horizon."

Woman: [Softly, with a hint of a smile] "And sometimes, if we’re lucky, we get to share that horizon with someone."

Man: [Pauses, looking into her eyes] "I’m glad I get to share this one with you."

Woman: [Smiling, her voice barely above a whisper] "Me too."

"""
emockpt = "Saved_Model"
sumckpt = "lora_bart1GAN_0_5.pth"
final_image, np_content_image, np_color_image = sdpipline(dialogue, sumckpt, emockpt, mode = "dialogue")



final_image, np_content_image, np_color_image = sdpipline(dialogue, sumckpt, emockpt, mode = "plain")

dialogue2 = """
Nick: (walking in slowly, head down, holding the test paper)
"Hey, Mom... I need to talk to you."

Mom: (looks up from the kitchen, noticing his demeanor)
"Nick? What’s wrong? Why do you look like that?"

Nick: (hesitantly handing her the test paper)
"I... I didn’t do well on the test. I got a 0."

Mom: (eyes widen, her voice sharpens)
"A 0? How could you get a 0, Nick? We’ve talked about this. You promised me you’d study harder this time!"

Nick: (eyes welling up, voice soft)
"I... I tried, Mom. I really did. I just... I couldn’t focus. Everything just felt so overwhelming."

Mom: (takes a deep breath, trying to stay calm but visibly upset)
"Overwhelming? Nick, this isn’t just about a test. This is about your future. If you keep getting 0s, where will that leave you? I can’t keep covering for you every time you mess up."

Nick: (voice shaking, avoiding eye contact)
"I know. I know, I messed up. But I don’t want to disappoint you. I just... I don’t know what happened."

Mom: (sighing deeply, her frustration turning into concern, walking over to him)
"I’m not just upset about the grade, Nick. I’m worried. I’m worried that you’re not taking this seriously, that you’re not trying your best. I’ve always believed in you, but I need to see you put in the effort. That’s all I’ve ever asked."

Nick: (voice cracking, trying to hold back tears)
"I am trying! It’s just... it feels like no matter how hard I try, I can’t get it right. I don’t want to disappoint you, Mom. I really don’t."

Mom: (softening, placing her hand on his shoulder, speaking gently now)
"I know you’re trying, Nick. I can see it. But trying isn’t enough if you’re not putting in the work. You have the potential, I know you do. But you need to take responsibility for your actions. This isn’t just about grades. It’s about showing up, every single day, and doing the best you can, even when it’s hard."

Nick: (sniffles, looking up at her, desperate for reassurance)
"I’ll do better, Mom. I promise. I don’t want to let you down again."

Mom: (sighs, pulling him into a hug)
"I know you don’t, sweetheart. Just remember, I’m not upset because I don’t love you—I’m upset because I know what you’re capable of, and I want to see you reach your full potential. We’ll figure this out together, okay?"

Nick: (nodding, tears rolling down his face)
"Okay, Mom. I’ll try harder. I’ll do better."

Mom: (pulling back, wiping his tears gently, offering a small smile)
"I know you will. And I’m here to help you every step of the way. We’ll work through this, together."
"""
final_image, np_content_image, np_color_image  = sdpipline(dialogue2, sumckpt, emockpt, mode = "dialogue")

final_image, np_content_image, np_color_image  = sdpipline(dialogue2, sumckpt, emockpt, mode = "plain")

dialouge3 = """
Man: (shouting, fists clenched)
"How dare you! I can't believe you did that! After everything I’ve done for you, this is how you repay me?!"

Other Person: (calm, trying to de-escalate)
"Hey, calm down. We can talk about this. Yelling isn’t going to solve anything."

Man: (furious, voice rising)
"Calm down? Calm down? You think I can just calm down after what you did?! You crossed a line, and now you expect me to just sit here and act like nothing happened?"

Other Person: (defensive, raising their voice slightly)
"I didn’t mean to hurt you. You’re blowing this out of proportion. Let’s just talk about it."

Man: (sarcastically)
"Talk? Oh, now you want to talk after everything?! Where was the talking when I needed it? You’ve done nothing but lie to me, and now you think I’m just supposed to forgive you?"

Other Person: (trying to stay composed, but growing frustrated)
"I never meant to lie to you, alright? Things just got out of hand. I’m sorry, but yelling at me isn’t going to fix it."

Man: (shaking his head, almost mocking)
"Sorry? You think ‘sorry’ is enough? You think I’m just going to forget what you did and move on like it’s no big deal?"

Other Person: (voice shaking slightly, feeling helpless)
"I didn’t want to hurt you. I messed up, but I’m not a monster. Please, just listen."

Man: (breathing heavily, eyes burning with anger)
"Listen? You want me to listen to you after everything you’ve done? No. I’ve had enough. I’m done with all of this."

Other Person: (pausing, trying to remain calm but hurting)
"I get that you're angry, I really do. But if we don’t at least try to talk this through, it’ll only get worse."

Man: (his voice starting to falter, frustration turning into exhaustion)
"I don't even know if I want to talk anymore... I’m so tired of feeling like I’m the only one who cares, the only one trying to make things right."

Other Person: (softening, stepping closer)
"I care. I do. And I’m sorry. I don’t know how to fix this, but I want to try. We can figure it out together."

Man: (silent for a moment, his anger slowly shifting to hurt, his voice quieter now)
"Sometimes I just feel like I’m always the one putting in all the effort, and you don’t even notice."

Other Person: (sincerely, with a tone of regret)
"I do notice. And I’m sorry I made you feel like that. I never wanted to hurt you. Let’s just... let’s figure this out, alright? Together."
"""

final_image, np_content_image, np_color_image  = sdpipline(dialouge3, sumckpt, emockpt, mode = "dialogue")

final_image, np_content_image, np_color_image  = sdpipline(dialouge3, sumckpt, emockpt, mode = "plain")

"""# some error with run.py"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

!python run.py -D "/content/Emotion_diffusion_project/example.txt" -Epath "/content/drive/MyDrive/COMP_8730_samsum/Testmodel/Saved_Model" -Spath "/content/drive/MyDrive/COMP_8730_samsum/Testmodel/lora_bart1GAN_0_5.pth" -mode "dialogue" -E True -S False -C False

"""# Training with GAN BART"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Emotion_diffusion_project/Model

!python main.py -o train -b 5 -e 1 -save true -l false -mode GAN

